apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vproapp.name}}
  labels:
    app: {{ .Values.vproapp.name}}
spec:
  replicas: {{ .Values.vproapp.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.vproapp.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.vproapp.name}}
    spec:

      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', "until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', "until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
      - name: init-rabbitmq
        image: busybox
        command: ['sh', '-c', "until nslookup vpromq01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]

      containers:
      - name: {{ .Values.vproapp.name}}
        image: {{ .Values.vproapp.image}}
        ports:
        - name: vproapp-port
          containerPort: {{ .Values.vproapp.port}}  