apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appservice.name}}
spec:
  selector: 
    app: {{ .Values.appservice.selector.app }} 
  ports:
  - port: {{ .Values.appservice.port}}
    protocol: TCP
    targetPort: vproapp-port
  type: ClusterIP  