apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbservice.name}}
spec:
  selector:
    app: {{ .Values.dbservice.selector.app}}
  ports:
  -  targetPort: vprodb-port
     port: {{ .Values.dbservice.port}}
     protocol: TCP
  type: ClusterIP     