apiVersion: v1
kind: Service
metadata:
  name: {{.Values.rabbitmqservice.name}}
spec:
  selector:
    app: {{.Values.rabbitmqservice.selector.app}}
  ports:
  - port: {{.Values.rabbitmqservice.port}}
    targetPort: vprormq-port
    protocol: TCP
  type: ClusterIP